parameters:
- name: environment_name
  type: string

jobs:
- deployment: destroy
  displayName: 'Destroy Infrastructure Changes'
  environment: ${{ parameters.environment_name }}
  timeoutInMinutes: 180
  strategy: 
    runOnce:
      deploy:
        steps:
          -checkout: self
          -scripts: |
            set -e
            terraform init -input=false \
              -backend-config="access=$(ARM_ACCESS_KEY)"
            terraform destroy -input=false -auto-approve -var-file="env/${{ parameters.environment_name }}/env.tfvars"
          name: 'TerraformDestroy'
          displayName: 'Terraform Destroy'
          timeoutInMinutes: 180
          env:
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)