parameters:
- name: environment_name
  type: string

jobs:
- deployment: plan
  displayName: 'Plan Infrastructure Changes'
  environment: ${{ parameters.environment_name }}
  strategy: 
    runOnce:
      deploy:
        steps:
          - checkout: self
          - script: |
              set -e
              terraform init -input=false \
                -backend-config="storage_account_name=$(BACKEND_STORAGE_ACCOUNT_NAME)" \
                -backend-config="container_name=$(BACKEND_CONTAINER_NAME)" \
                -backend-config="key=$(BACKEND_KEY_NAME)" \
                -backend-config="access_key=$(BACKEND_ACCESS_KEY)" 
              terraform plan -input=false -var-file="env/${{ parameters.environment_name }}/env.tfvars"
            name: 'TerraformPlan'
            displayName: 'Terraform Plan'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)