trigger: none

resources:
- repo: self

pool: 
  vmImage: 'ubuntu-latest'

variables:
- group: vg-helloworld-prd

extends:
  template: ../../pipeline-templates/tf-apply.yml
  parameters:
    environment_name: 'prd'